# Generated by Django 6.0.4 on 2026-04-22 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('key_encrypted', models.TextField()),
                ('key_suffix', models.CharField(max_length=4)),
                ('plan', models.CharField(default='unknown', max_length=20)),
                ('last_used', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_emotion_tag', models.BooleanField(default=True)),
                ('require_notes', models.BooleanField(default=False)),
                ('default_trade_type', models.CharField(default='BUY', max_length=4)),
                ('default_fee_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('confirm_before_save', models.BooleanField(default=False)),
                ('default_date', models.CharField(default='today', max_length=20)),
                ('ai_tone', models.CharField(default='direct_kind', max_length=20)),
                ('auto_generate_ai', models.BooleanField(default=False)),
                ('ai_include_notes', models.BooleanField(default=True)),
                ('ai_context_months', models.IntegerField(default=3)),
                ('pnl_format', models.CharField(default='dollar', max_length=10)),
                ('decimal_places', models.IntegerField(default=4)),
                ('dashboard_period', models.CharField(default='1m', max_length=5)),
                ('show_unrealized', models.BooleanField(default=True)),
                ('notify_monthly', models.BooleanField(default=True)),
                ('notify_untagged', models.BooleanField(default=True)),
                ('notify_weekly', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
