# Generated by Django 6.0.4 on 2026-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usersession_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeedback',
            name='month_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
