# Generated by Django 6.0.4 on 2026-04-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aifeedback_month_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
