# Generated by Django 6.0.4 on 2026-05-01 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_apikey_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emotiontag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotion_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emotiontag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='emotiontag',
            unique_together={('user', 'name')},
        ),
    ]
